version: 2
updates:
    -
        package-ecosystem: composer
        directory: "/"
        schedule:
            interval: monthly
        versioning-strategy: lockfile-only
        groups:
            prod-dependencies:
                dependency-type: production
            dev-dependencies:
                dependency-type: development
